// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"week04.myapp/app/shop/interface/internal/biz"
	"week04.myapp/app/shop/interface/internal/data"
	"week04.myapp/app/shop/interface/internal/server"
	"week04.myapp/app/shop/interface/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	fakeDB := data.NewFakeDB()
	dataData := data.NewData(fakeDB)
	goodsRepo := data.NewGoodsRepo(dataData)
	goodsUseCase := biz.NewGoodsUseCase(goodsRepo)
	shopInterface := service.NewShopInterface(goodsUseCase)
	httpServer := server.NewHTTPServer(shopInterface)
	grpcServer := server.NewGRPCServer(shopInterface)
	app := newApp(httpServer, grpcServer)
	return app, nil
}
