// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"week13.myapp/app/goods/service/internal/biz"
	"week13.myapp/app/goods/service/internal/data"
	"week13.myapp/app/goods/service/internal/server"
	"week13.myapp/app/goods/service/internal/service"
)

// Injectors from wire.go:

func initApp() (*kratos.App, error) {
	goodsRepo := data.NewGoodsRepo()
	goodsUseCase := biz.NewGoodsUseCase(goodsRepo)
	goodsService := service.NewGoodsService(goodsUseCase)
	grpcServer := server.NewGRPCServer(goodsService)
	app := newApp(grpcServer)
	return app, nil
}
